name: Build and upload nuget package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/EugeneEX/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - run: dotnet build --configuration Release src/CityRide.Kafka/CityRide.Kafka.csproj
      - name: Create the package
        run: dotnet pack --configuration Release src/CityRide.Kafka/CityRide.Kafka.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push src/CityRide.Kafka/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}}
